### ISSUE TITLE
Video is blurry

### ISSUE THREAD

**Issue by sumitkr2000** [CatsInTech/GitHub-ReadMe#21] opened 2023-05-28 08:16 UTC
Hey @praveenscience the video on the home page is not properly visible. I want to add a video. Please assign me this issue. Thank you!

**Comment by praveenscience** [comment] 2023-05-28 08:41
Duplicate of #11. Kindly look at previous issues before creating new ones. Don't duplicate. 😊

**Closed by praveenscience** 2023-05-28 08:41 UTC

**Comment by sumitkr2000** [comment] 2023-05-28 14:09
Ok sorry
